### ISSUE TITLE
Add throttle to scrollHandler

### ISSUE THREAD

**Issue by kogutich** [barklan/hugo-dead-simple#11]
Hi, great theme, I'm using your approach for dynamic toc in my theme.
One suggestion - add throttle to minimize calls for scroll handler:
https://github.com/barklan/hugo-dead-simple/blob/de7287d81664f397c467a7c76736e5cc8ca4b7b2/layouts/partials/footer_scripts.html#L44C5-L44C52

**Comment by barklan** [comment]
Thanks, nice suggestion. Added 300ms throttle in v1.75.59
