### ISSUE TITLE
Example site is down

### ISSUE THREAD

**Issue by Fabrice-Bernes** [barklan/hugo-dead-simple#8]
I don't know if this is the right place to report this, but the link to the [demo site](https://rxsamira.netlify.app/post/hugo-dead-simple/)  is returning 404.

That site was a really good reference for the syntax. If it's not going to be online anymore then maybe it should be added to this repo? Some hugo themes include an `exampleSite` folder with the source code to the demo.

**Comment by YoungjuWang** [comment]
@barklan Check this issue please. I want to use and configure dead-simple theme with hugo :).

**Comment by dtosti** [comment]
@barklan Hello, I understand you may have more urgent and pressing issues to solve, but the example site is still down, rendering your work pretty useless, IMHO.

**Comment by barklan** [comment]
Example site is up at https://hugo-dead-simple.netlify.app/. Apologies for delay
